# Generated by Snowflake Copilot
# Import python packages
import streamlit as st
import plotly
from snowflake.snowpark.context import get_active_session
# Import required packages
import plotly.graph_objects as go
import pandas as pd

# import app pages
# from sql.org_billable_credits import org_billable_usage


from plotly.subplots import make_subplots
session = get_active_session()

# To create a new page, create a new file in the pages directory, use the template new_page_template.py
# add the name of the page to the page list 
# page = st.sidebar.selectbox("Choose a page:", ["Overview", "Organization Billable Credits",..."New Page")
# then add a new elif condition that imports the page and class
# elif page == "New Page":
#     from pages.new_page import new_page
#     new_page()
     
# Create sidebar with navigation
st.sidebar.title("Navigation")
page = st.sidebar.selectbox("Choose a page:", ["Overview", "Organization Billable Credits", "Organization Capacity Burndown","Organization Credit Usage History",
                                               "Organization Usage History by Object","Organization Usage History"])

# Write directly to the app
if page == "Overview":
    st.title("Overview :balloon:")
    st.write("Welcome to the Snowflake Usage Dashboard")
    
elif page == "Organization Billable Credits":
    from pages.organization_billable_credits import org_billable_credits
    org_billable_credits()
elif page == "Organization Capacity Burndown":
    from pages.organization_capacity_burndown import org_capacity_burndown
    org_capacity_burndown()
elif page == "Organization Credit Usage History":
    from pages.organization_credit_usage_history import org_credit_usage
    org_credit_usage()
elif page == "Organization Usage History by Object":
    from pages.organization_usage_history_by_object import org_usage_history_by_object
    org_usage_history_by_object()
elif page == "Organization Usage History":
    from pages.organization_usage_history import org_usage_history
    org_usage_history()


