# Generated by Snowflake Copilot
# Import python packages
import streamlit as st
import plotly
from snowflake.snowpark.context import get_active_session
# Import required packages
import plotly.graph_objects as go
import pandas as pd

# import app pages
# from sql.org_billable_credits import org_billable_usage


from plotly.subplots import make_subplots
session = get_active_session()
     
# Create sidebar with navigation
st.sidebar.title("Navigation")
page = st.sidebar.selectbox("Choose a page:", ["Overview", "Organization Billable Credits", "Organization Capacity Burndown"])

# Write directly to the app
if page == "Overview":
    st.title("Overview :balloon:")
    st.write("Welcome to the Snowflake Usage Dashboard")
    
elif page == "Organization Billable Credits":
    from pages.organization_billable_credits import org_billable_credits
    org_billable_credits()
elif page == "Organization Capacity Burndown":
    from pages.organization_capacity_burndown import org_capacity_burndown
    org_capacity_burndown()




